### ISSUE TITLE
🎨 Adjust colors of realm-selection-view

### ISSUE THREAD

**Issue by TGotwig** [TGotwig/flippy-panda#29]
![image](https://user-images.githubusercontent.com/30773779/97699971-54d66a80-1aab-11eb-8545-17a3e4c4b7e2.png)

**Comment by vaisakhDev** [comment]
Hey @TGotwig, can I give this a go?

**Comment by TGotwig** [comment]
Hello @vaisakhDev 👋
Yes you can 😊 Thanks! 🚀
You can also open pull-request without an corresponding issue if you like 😊

**Comment by vaisakhDev** [comment]
> Hello @vaisakhDev 
> Yes you can  Thanks! 
> You can also open pull-requests without an corresponding issue if you like

Sure!! :handshake:

**Comment by vaisakhDev** [comment]
@TGotwig Are you okay with these colors? :art: 
![image](https://user-images.githubusercontent.com/44577910/97729375-ace78e00-1af8-11eb-9125-6beb183feb48.png)

**Comment by TGotwig** [comment]
Would say that orange-fill behind the selection is a little bit too intense 🧐

**Comment by TGotwig** [comment]
@vaisakhDev Thank you very much! Looks great! 😊 🎨
